[root@bng-p3-vmm-server-dcbg network]# nosetests test_routers.py > error1
....FFFF.FFFFF
======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_create_router_with_default_snat_value[id-847257cc-6afd-4154-b8fb-af49f5670ce8]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:03:35,489 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_create_router_with_default_snat_value): 404 POST http://10.206.44.175:9696/v2.0/routers 0.114s
2015-12-18 14:03:35,489 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router-1557335746", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:35 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-3e5ee4c0-8be0-4ad6-9978-8104cb89f8ff'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/test.py", line 171, in wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 110, in test_create_router_with_default_snat_value
    name, external_network_id=CONF.network.public_network_id)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/base_routers.py", line 32, in _create_router
    external_network_id, enable_snat)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/base.py", line 272, in create_router
    admin_state_up=admin_state_up, **kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 297, in create_router
    resp, body = self.post(uri, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 252, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 675, in _error_checker
    raise exceptions.NotFound(resp_body)
NotFound: Object not found
Details: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_create_router_with_default_snat_value): 404 POST http://10.206.44.175:9696/v2.0/routers 0.114s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router-1557335746", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:35 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-3e5ee4c0-8be0-4ad6-9978-8104cb89f8ff'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_create_router_with_snat_explicit[id-ea74068d-09e9-4fd7-8995-9b6a1ace920f]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:03:35,737 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_create_router_with_snat_explicit): 404 POST http://10.206.44.175:9696/v2.0/routers 0.245s
2015-12-18 14:03:35,737 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9", "enable_snat": false}, "name": "snat-router-1676428452", "admin_state_up": true}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:35 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-b54ddabe-ed43-461f-9441-83c6b6231a79'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/test.py", line 171, in wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 126, in test_create_router_with_snat_explicit
    name, external_gateway_info=external_gateway_info)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 297, in create_router
    resp, body = self.post(uri, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 252, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 675, in _error_checker
    raise exceptions.NotFound(resp_body)
NotFound: Object not found
Details: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_create_router_with_snat_explicit): 404 POST http://10.206.44.175:9696/v2.0/routers 0.245s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9", "enable_snat": false}, "name": "snat-router-1676428452", "admin_state_up": true}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:35 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-b54ddabe-ed43-461f-9441-83c6b6231a79'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_create_show_list_update_delete_router[id-f64403e2-8483-4b34-8ccd-b09a87bcc68c,smoke]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:03:36,061 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_create_show_list_update_delete_router): 404 POST http://10.206.44.175:9696/v2.0/routers 0.322s
2015-12-18 14:03:36,062 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router--179327585", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:36 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-8b40cdf7-7ea2-4219-814d-f14580fd90e4'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 58, in test_create_show_list_update_delete_router
    admin_state_up=False)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 297, in create_router
    resp, body = self.post(uri, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 252, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 675, in _error_checker
    raise exceptions.NotFound(resp_body)
NotFound: Object not found
Details: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_create_show_list_update_delete_router): 404 POST http://10.206.44.175:9696/v2.0/routers 0.322s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router--179327585", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:36 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-8b40cdf7-7ea2-4219-814d-f14580fd90e4'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_update_extra_route[id-c86ac3a8-50bd-4b00-a6b8-62af84a0765c]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:03:36,117 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_extra_route): 201 POST http://10.206.44.175:9696/v2.0/networks 0.053s
2015-12-18 14:03:36,117 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"network": {"name": "test-network--1760458973"}}
    Response - Headers: {'status': '201', 'content-length': '364', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:36 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-a5b0b445-ed82-41ac-9177-5b9a160e15d6'}
        Body: {"network": {"status": "ACTIVE", "subnets": [], "name": "test-network--1760458973", "provider:physical_network": "physnet1", "router:external": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "admin_state_up": true, "mtu": 0, "shared": false, "provider:network_type": "vlan", "id": "a820afb8-31fc-4a34-a56a-984fe8fca713", "provider:segmentation_id": 1001}}
2015-12-18 14:03:36,476 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_extra_route): 201 POST http://10.206.44.175:9696/v2.0/subnets 0.358s
2015-12-18 14:03:36,477 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"subnet": {"ip_version": 4, "network_id": "a820afb8-31fc-4a34-a56a-984fe8fca713", "cidr": "10.100.0.0/28", "gateway_ip": "10.100.0.1"}}
    Response - Headers: {'status': '201', 'content-length': '447', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:36 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-99aef6c2-a34f-48c0-9073-34982c9ccb0f'}
        Body: {"subnet": {"name": "", "enable_dhcp": true, "network_id": "a820afb8-31fc-4a34-a56a-984fe8fca713", "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "dns_nameservers": [], "gateway_ip": "10.100.0.1", "ipv6_ra_mode": null, "allocation_pools": [{"start": "10.100.0.2", "end": "10.100.0.14"}], "host_routes": [], "ip_version": 4, "ipv6_address_mode": null, "cidr": "10.100.0.0/28", "id": "66721061-ee28-4e0e-8651-fe0febf44c66", "subnetpool_id": null}}
2015-12-18 14:03:45,638 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_extra_route): 500 POST http://10.206.44.175:9696/v2.0/routers 9.161s
2015-12-18 14:03:45,639 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {}, "name": "router--890915996", "admin_state_up": true}}
    Response - Headers: {'status': '500', 'content-length': '150', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:45 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-6fe2067c-fe2c-4d09-84b7-f243d2f459dc'}
        Body: {"NeutronError": {"message": "Request Failed: internal server error while processing your request.", "type": "HTTPInternalServerError", "detail": ""}}
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/test.py", line 171, in wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 278, in test_update_extra_route
    data_utils.rand_name('router-'), True)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/base_routers.py", line 32, in _create_router
    external_network_id, enable_snat)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/base.py", line 272, in create_router
    admin_state_up=admin_state_up, **kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 297, in create_router
    resp, body = self.post(uri, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 252, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 734, in _error_checker
    raise exceptions.ServerFault(message)
ServerFault: Got server fault
Details: Request Failed: internal server error while processing your request.

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_extra_route): 201 POST http://10.206.44.175:9696/v2.0/networks 0.053s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"network": {"name": "test-network--1760458973"}}
    Response - Headers: {'status': '201', 'content-length': '364', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:36 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-a5b0b445-ed82-41ac-9177-5b9a160e15d6'}
        Body: {"network": {"status": "ACTIVE", "subnets": [], "name": "test-network--1760458973", "provider:physical_network": "physnet1", "router:external": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "admin_state_up": true, "mtu": 0, "shared": false, "provider:network_type": "vlan", "id": "a820afb8-31fc-4a34-a56a-984fe8fca713", "provider:segmentation_id": 1001}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_extra_route): 201 POST http://10.206.44.175:9696/v2.0/subnets 0.358s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"subnet": {"ip_version": 4, "network_id": "a820afb8-31fc-4a34-a56a-984fe8fca713", "cidr": "10.100.0.0/28", "gateway_ip": "10.100.0.1"}}
    Response - Headers: {'status': '201', 'content-length': '447', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:36 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-99aef6c2-a34f-48c0-9073-34982c9ccb0f'}
        Body: {"subnet": {"name": "", "enable_dhcp": true, "network_id": "a820afb8-31fc-4a34-a56a-984fe8fca713", "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "dns_nameservers": [], "gateway_ip": "10.100.0.1", "ipv6_ra_mode": null, "allocation_pools": [{"start": "10.100.0.2", "end": "10.100.0.14"}], "host_routes": [], "ip_version": 4, "ipv6_address_mode": null, "cidr": "10.100.0.0/28", "id": "66721061-ee28-4e0e-8651-fe0febf44c66", "subnetpool_id": null}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_extra_route): 500 POST http://10.206.44.175:9696/v2.0/routers 9.161s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {}, "name": "router--890915996", "admin_state_up": true}}
    Response - Headers: {'status': '500', 'content-length': '150', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:33:45 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-6fe2067c-fe2c-4d09-84b7-f243d2f459dc'}
        Body: {"NeutronError": {"message": "Request Failed: internal server error while processing your request.", "type": "HTTPInternalServerError", "detail": ""}}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_update_router_reset_gateway_without_snat[id-f2faf994-97f4-410b-a831-9bc977b64374]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:04:00,501 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_reset_gateway_without_snat): 404 POST http://10.206.44.175:9696/v2.0/routers 0.043s
2015-12-18 14:04:00,501 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router--687275697", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:00 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-32b70d85-524e-424b-9521-18b67b68bb62'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/test.py", line 171, in wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 258, in test_update_router_reset_gateway_without_snat
    external_network_id=CONF.network.public_network_id)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/base_routers.py", line 32, in _create_router
    external_network_id, enable_snat)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/base.py", line 272, in create_router
    admin_state_up=admin_state_up, **kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 297, in create_router
    resp, body = self.post(uri, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 252, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 675, in _error_checker
    raise exceptions.NotFound(resp_body)
NotFound: Object not found
Details: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_reset_gateway_without_snat): 404 POST http://10.206.44.175:9696/v2.0/routers 0.043s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router--687275697", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:00 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-32b70d85-524e-424b-9521-18b67b68bb62'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_update_router_set_gateway[id-6cc285d8-46bf-4f36-9b1a-783e3008ba79]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:04:08,248 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway): 201 POST http://10.206.44.175:9696/v2.0/routers 7.744s
2015-12-18 14:04:08,248 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {}, "name": "router--1381043004", "admin_state_up": false}}
    Response - Headers: {'status': '201', 'content-length': '213', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:08 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-9684dfaf-a75d-4db8-b0db-150c9d27e130'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--1381043004", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "9933941e-5177-4812-b07c-c94a1908a936"}}
2015-12-18 14:04:08,280 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway): 200 GET http://10.206.44.175:9696/v2.0/routers/9933941e-5177-4812-b07c-c94a1908a936 0.031s
2015-12-18 14:04:08,280 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '213', 'content-location': 'http://10.206.44.175:9696/v2.0/routers/9933941e-5177-4812-b07c-c94a1908a936', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:08 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-81664244-ec74-4e3d-b7f9-64cb1f431358'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--1381043004", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "9933941e-5177-4812-b07c-c94a1908a936"}}
2015-12-18 14:04:08,374 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway): 404 PUT http://10.206.44.175:9696/v2.0/routers/9933941e-5177-4812-b07c-c94a1908a936 0.093s
2015-12-18 14:04:08,374 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router--1381043004", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:08 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-c2a861ec-c73d-4cd3-826d-b91257f89bac'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
2015-12-18 14:04:08,394 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:_run_cleanups): 200 GET http://10.206.44.175:9696/v2.0/ports?device_id=9933941e-5177-4812-b07c-c94a1908a936 0.019s
2015-12-18 14:04:08,394 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '13', 'content-location': 'http://10.206.44.175:9696/v2.0/ports?device_id=9933941e-5177-4812-b07c-c94a1908a936', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:08 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-4fd063e3-2449-463a-9e8b-d0292e6f3054'}
        Body: {"ports": []}
2015-12-18 14:04:18,681 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:_run_cleanups): 204 DELETE http://10.206.44.175:9696/v2.0/routers/9933941e-5177-4812-b07c-c94a1908a936 10.286s
2015-12-18 14:04:18,681 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Fri, 18 Dec 2015 08:34:18 GMT', 'status': '204', 'connection': 'close', 'content-length': '0', 'x-openstack-request-id': 'req-5cb2a824-9ec4-4adc-b204-36104ac8feba'}
        Body:
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 203, in test_update_router_set_gateway
    'network_id': CONF.network.public_network_id})
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 338, in update_router
    return self._update_router(router_id, set_enable_snat=False, **kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 326, in _update_router
    resp, body = self.put(uri, update_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 315, in put
    return self.request('PUT', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 675, in _error_checker
    raise exceptions.NotFound(resp_body)
NotFound: Object not found
Details: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway): 201 POST http://10.206.44.175:9696/v2.0/routers 7.744s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {}, "name": "router--1381043004", "admin_state_up": false}}
    Response - Headers: {'status': '201', 'content-length': '213', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:08 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-9684dfaf-a75d-4db8-b0db-150c9d27e130'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--1381043004", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "9933941e-5177-4812-b07c-c94a1908a936"}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway): 200 GET http://10.206.44.175:9696/v2.0/routers/9933941e-5177-4812-b07c-c94a1908a936 0.031s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '213', 'content-location': 'http://10.206.44.175:9696/v2.0/routers/9933941e-5177-4812-b07c-c94a1908a936', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:08 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-81664244-ec74-4e3d-b7f9-64cb1f431358'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--1381043004", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "9933941e-5177-4812-b07c-c94a1908a936"}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway): 404 PUT http://10.206.44.175:9696/v2.0/routers/9933941e-5177-4812-b07c-c94a1908a936 0.093s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router--1381043004", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:08 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-c2a861ec-c73d-4cd3-826d-b91257f89bac'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:_run_cleanups): 200 GET http://10.206.44.175:9696/v2.0/ports?device_id=9933941e-5177-4812-b07c-c94a1908a936 0.019s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '13', 'content-location': 'http://10.206.44.175:9696/v2.0/ports?device_id=9933941e-5177-4812-b07c-c94a1908a936', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:08 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-4fd063e3-2449-463a-9e8b-d0292e6f3054'}
        Body: {"ports": []}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:_run_cleanups): 204 DELETE http://10.206.44.175:9696/v2.0/routers/9933941e-5177-4812-b07c-c94a1908a936 10.286s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Fri, 18 Dec 2015 08:34:18 GMT', 'status': '204', 'connection': 'close', 'content-length': '0', 'x-openstack-request-id': 'req-5cb2a824-9ec4-4adc-b204-36104ac8feba'}
        Body: 
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_update_router_set_gateway_with_snat_explicit[id-b386c111-3b21-466d-880c-5e72b01e1a33]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:04:25,970 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway_with_snat_explicit): 201 POST http://10.206.44.175:9696/v2.0/routers 7.287s
2015-12-18 14:04:25,971 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {}, "name": "router--1894083658", "admin_state_up": false}}
    Response - Headers: {'status': '201', 'content-length': '213', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:25 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-49b2d33c-04ab-47a8-9e69-20905d806de2'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--1894083658", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "ebc33658-3bd8-4a2e-a2b7-587066186d85"}}
2015-12-18 14:04:26,074 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway_with_snat_explicit): 200 GET http://10.206.44.175:9696/v2.0/routers/ebc33658-3bd8-4a2e-a2b7-587066186d85 0.103s
2015-12-18 14:04:26,075 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '213', 'content-location': 'http://10.206.44.175:9696/v2.0/routers/ebc33658-3bd8-4a2e-a2b7-587066186d85', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:26 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-b04abcab-1927-4ab4-bbbb-26fe3fca03a1'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--1894083658", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "ebc33658-3bd8-4a2e-a2b7-587066186d85"}}
2015-12-18 14:04:26,163 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway_with_snat_explicit): 404 PUT http://10.206.44.175:9696/v2.0/routers/ebc33658-3bd8-4a2e-a2b7-587066186d85 0.088s
2015-12-18 14:04:26,163 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9", "enable_snat": true}, "name": "router--1894083658", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:26 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-08c2c4b2-eefa-4260-b9ed-ce1ec5664df7'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
2015-12-18 14:04:26,183 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:_run_cleanups): 200 GET http://10.206.44.175:9696/v2.0/ports?device_id=ebc33658-3bd8-4a2e-a2b7-587066186d85 0.018s
2015-12-18 14:04:26,183 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '13', 'content-location': 'http://10.206.44.175:9696/v2.0/ports?device_id=ebc33658-3bd8-4a2e-a2b7-587066186d85', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:26 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-cb4fb68d-ba0f-4e2a-8761-6bb09dd1741d'}
        Body: {"ports": []}
2015-12-18 14:04:33,853 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:_run_cleanups): 204 DELETE http://10.206.44.175:9696/v2.0/routers/ebc33658-3bd8-4a2e-a2b7-587066186d85 7.670s
2015-12-18 14:04:33,854 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Fri, 18 Dec 2015 08:34:33 GMT', 'status': '204', 'connection': 'close', 'content-length': '0', 'x-openstack-request-id': 'req-67df0b08-8b9b-4384-98f8-4b4cb1a7579b'}
        Body:
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/test.py", line 171, in wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 218, in test_update_router_set_gateway_with_snat_explicit
    'enable_snat': True})
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 346, in update_router_with_snat_gw_info
    return self._update_router(router_id, set_enable_snat=True, **kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 326, in _update_router
    resp, body = self.put(uri, update_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 315, in put
    return self.request('PUT', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 675, in _error_checker
    raise exceptions.NotFound(resp_body)
NotFound: Object not found
Details: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway_with_snat_explicit): 201 POST http://10.206.44.175:9696/v2.0/routers 7.287s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {}, "name": "router--1894083658", "admin_state_up": false}}
    Response - Headers: {'status': '201', 'content-length': '213', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:25 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-49b2d33c-04ab-47a8-9e69-20905d806de2'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--1894083658", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "ebc33658-3bd8-4a2e-a2b7-587066186d85"}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway_with_snat_explicit): 200 GET http://10.206.44.175:9696/v2.0/routers/ebc33658-3bd8-4a2e-a2b7-587066186d85 0.103s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '213', 'content-location': 'http://10.206.44.175:9696/v2.0/routers/ebc33658-3bd8-4a2e-a2b7-587066186d85', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:26 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-b04abcab-1927-4ab4-bbbb-26fe3fca03a1'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--1894083658", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "ebc33658-3bd8-4a2e-a2b7-587066186d85"}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway_with_snat_explicit): 404 PUT http://10.206.44.175:9696/v2.0/routers/ebc33658-3bd8-4a2e-a2b7-587066186d85 0.088s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9", "enable_snat": true}, "name": "router--1894083658", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:26 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-08c2c4b2-eefa-4260-b9ed-ce1ec5664df7'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:_run_cleanups): 200 GET http://10.206.44.175:9696/v2.0/ports?device_id=ebc33658-3bd8-4a2e-a2b7-587066186d85 0.018s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '13', 'content-location': 'http://10.206.44.175:9696/v2.0/ports?device_id=ebc33658-3bd8-4a2e-a2b7-587066186d85', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:26 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-cb4fb68d-ba0f-4e2a-8761-6bb09dd1741d'}
        Body: {"ports": []}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:_run_cleanups): 204 DELETE http://10.206.44.175:9696/v2.0/routers/ebc33658-3bd8-4a2e-a2b7-587066186d85 7.670s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Fri, 18 Dec 2015 08:34:33 GMT', 'status': '204', 'connection': 'close', 'content-length': '0', 'x-openstack-request-id': 'req-67df0b08-8b9b-4384-98f8-4b4cb1a7579b'}
        Body: 
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_update_router_set_gateway_without_snat[id-96536bc7-8262-4fb2-9967-5c46940fa279]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:04:42,354 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway_without_snat): 201 POST http://10.206.44.175:9696/v2.0/routers 8.499s
2015-12-18 14:04:42,355 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {}, "name": "router--700386638", "admin_state_up": false}}
    Response - Headers: {'status': '201', 'content-length': '212', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:42 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-14c7fa1e-ac51-4eb7-baaf-c6b9c1a8964e'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--700386638", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "d83c7000-0b0f-4f0e-b412-aefa43706847"}}
2015-12-18 14:04:42,451 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway_without_snat): 200 GET http://10.206.44.175:9696/v2.0/routers/d83c7000-0b0f-4f0e-b412-aefa43706847 0.096s
2015-12-18 14:04:42,452 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '212', 'content-location': 'http://10.206.44.175:9696/v2.0/routers/d83c7000-0b0f-4f0e-b412-aefa43706847', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:42 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-3696dd2a-0d6e-417b-8719-3452ddf37420'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--700386638", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "d83c7000-0b0f-4f0e-b412-aefa43706847"}}
2015-12-18 14:04:42,627 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_set_gateway_without_snat): 404 PUT http://10.206.44.175:9696/v2.0/routers/d83c7000-0b0f-4f0e-b412-aefa43706847 0.174s
2015-12-18 14:04:42,627 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9", "enable_snat": false}, "name": "router--700386638", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:42 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-e4068792-cf78-4083-9fc2-fd326313c633'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
2015-12-18 14:04:42,648 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:_run_cleanups): 200 GET http://10.206.44.175:9696/v2.0/ports?device_id=d83c7000-0b0f-4f0e-b412-aefa43706847 0.020s
2015-12-18 14:04:42,649 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '13', 'content-location': 'http://10.206.44.175:9696/v2.0/ports?device_id=d83c7000-0b0f-4f0e-b412-aefa43706847', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:42 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-07d76939-f021-4478-9195-e5032aa92682'}
        Body: {"ports": []}
2015-12-18 14:04:50,617 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:_run_cleanups): 204 DELETE http://10.206.44.175:9696/v2.0/routers/d83c7000-0b0f-4f0e-b412-aefa43706847 7.967s
2015-12-18 14:04:50,617 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Fri, 18 Dec 2015 08:34:50 GMT', 'status': '204', 'connection': 'close', 'content-length': '0', 'x-openstack-request-id': 'req-7162aeb7-4f88-4120-9a29-554cf9433f77'}
        Body:
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/test.py", line 171, in wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 233, in test_update_router_set_gateway_without_snat
    'enable_snat': False})
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 346, in update_router_with_snat_gw_info
    return self._update_router(router_id, set_enable_snat=True, **kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 326, in _update_router
    resp, body = self.put(uri, update_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 315, in put
    return self.request('PUT', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 675, in _error_checker
    raise exceptions.NotFound(resp_body)
NotFound: Object not found
Details: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway_without_snat): 201 POST http://10.206.44.175:9696/v2.0/routers 8.499s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {}, "name": "router--700386638", "admin_state_up": false}}
    Response - Headers: {'status': '201', 'content-length': '212', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:42 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-14c7fa1e-ac51-4eb7-baaf-c6b9c1a8964e'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--700386638", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "d83c7000-0b0f-4f0e-b412-aefa43706847"}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway_without_snat): 200 GET http://10.206.44.175:9696/v2.0/routers/d83c7000-0b0f-4f0e-b412-aefa43706847 0.096s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '212', 'content-location': 'http://10.206.44.175:9696/v2.0/routers/d83c7000-0b0f-4f0e-b412-aefa43706847', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:42 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-3696dd2a-0d6e-417b-8719-3452ddf37420'}
        Body: {"router": {"status": "ACTIVE", "external_gateway_info": null, "name": "router--700386638", "admin_state_up": false, "tenant_id": "519f94289ac34ee7baea23f0950f9c4e", "id": "d83c7000-0b0f-4f0e-b412-aefa43706847"}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_set_gateway_without_snat): 404 PUT http://10.206.44.175:9696/v2.0/routers/d83c7000-0b0f-4f0e-b412-aefa43706847 0.174s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9", "enable_snat": false}, "name": "router--700386638", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:42 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-e4068792-cf78-4083-9fc2-fd326313c633'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:_run_cleanups): 200 GET http://10.206.44.175:9696/v2.0/ports?device_id=d83c7000-0b0f-4f0e-b412-aefa43706847 0.020s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'status': '200', 'content-length': '13', 'content-location': 'http://10.206.44.175:9696/v2.0/ports?device_id=d83c7000-0b0f-4f0e-b412-aefa43706847', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:42 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-07d76939-f021-4478-9195-e5032aa92682'}
        Body: {"ports": []}
tempest_lib.common.rest_client: INFO: Request (RoutersTest:_run_cleanups): 204 DELETE http://10.206.44.175:9696/v2.0/routers/d83c7000-0b0f-4f0e-b412-aefa43706847 7.967s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: None
    Response - Headers: {'date': 'Fri, 18 Dec 2015 08:34:50 GMT', 'status': '204', 'connection': 'close', 'content-length': '0', 'x-openstack-request-id': 'req-7162aeb7-4f88-4120-9a29-554cf9433f77'}
        Body: 
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.network.test_routers.RoutersTest.test_update_router_unset_gateway[id-ad81b7ee-4f81-407b-a19c-17e623f763e8]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2015-12-18 14:04:50,746 22459 INFO     [tempest_lib.common.rest_client] Request (RoutersTest:test_update_router_unset_gateway): 404 POST http://10.206.44.175:9696/v2.0/routers 0.127s
2015-12-18 14:04:50,746 22459 DEBUG    [tempest_lib.common.rest_client] Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router--395811548", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:50 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-2b7e08db-6160-4b59-bdc2-dae0504275b6'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
}}}

Traceback (most recent call last):
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/test_routers.py", line 244, in test_update_router_unset_gateway
    external_network_id=CONF.network.public_network_id)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/base_routers.py", line 32, in _create_router
    external_network_id, enable_snat)
  File "/usr/share/openstack-tempest-kilo/tempest/api/network/base.py", line 272, in create_router
    admin_state_up=admin_state_up, **kwargs)
  File "/usr/share/openstack-tempest-kilo/tempest/services/network/json/network_client.py", line 297, in create_router
    resp, body = self.post(uri, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 252, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 629, in request
    resp, resp_body)
  File "/usr/lib/python2.7/site-packages/tempest_lib/common/rest_client.py", line 675, in _error_checker
    raise exceptions.NotFound(resp_body)
NotFound: Object not found
Details: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}

-------------------- >> begin captured logging << --------------------
tempest_lib.common.rest_client: INFO: Request (RoutersTest:test_update_router_unset_gateway): 404 POST http://10.206.44.175:9696/v2.0/routers 0.127s
tempest_lib.common.rest_client: DEBUG: Request - Headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Auth-Token': '<omitted>'}
        Body: {"router": {"external_gateway_info": {"network_id": "0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9"}, "name": "router--395811548", "admin_state_up": false}}
    Response - Headers: {'status': '404', 'content-length': '137', 'connection': 'close', 'date': 'Fri, 18 Dec 2015 08:34:50 GMT', 'content-type': 'application/json; charset=UTF-8', 'x-openstack-request-id': 'req-2b7e08db-6160-4b59-bdc2-dae0504275b6'}
        Body: {"NeutronError": {"message": "Network 0cd9f802-fdee-4a15-bf6a-4fa641ce0fd9 could not be found", "type": "NetworkNotFound", "detail": ""}}
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 14 tests in 303.193s

FAILED (failures=9)
[root@bng-p3-vmm-server-dcbg network]# cat error1 
[root@bng-p3-vmm-server-dcbg network]# 

